version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    ports:
      - 8000:80
    restart: always
    volumes:
      - postfixadmin:/var/www/html
    environment:
      TZ: Asia/Bangkok
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: $MYSQL_USER
      POSTFIXADMIN_DB_NAME: $MYSQL_DATABASE
      POSTFIXADMIN_DB_PASSWORD: $MYSQL_PASSWORD
networks:
  default:
    name: postfixadmin
volumes:
  postfixadmin:
  db-data:
  db-config:
  
